### ISSUE TITLE
Download all word embeddings

### ISSUE THREAD

**Issue by karvesaket** [nikhgarg/EmbeddingDynamicStereotypes#1]
I am trying to re-run your code and have been struggling to find all the word embeddings you used during your experiments. Could you please let me know from where do I download them? Also, could you elaborate on exactly how do I run your code? The README does not help me a lot.

Thank You

**Comment by nikhgarg** [comment]
Which embeddings in particular can you not find? The README links to each embedding, and the links were live last time I checked.

**Comment by karvesaket** [comment]
I was not able to find the SGNS and SVD embeddings (there were many links on the page the README linked to). However, I figured it out. It also took me some time to figure out the required directory structure to be able to run the code as is. I am planning to make a bash script to download and run everything at once and make a PR to the repo.

Thanks!
