### ISSUE TITLE
New York Times Annotated Corpus link returns 404

### ISSUE THREAD

**Issue by raffaelemancuso** [nikhgarg/EmbeddingDynamicStereotypes#5]
The link to the New York Times Annotated Corpus in README.md is wrong and returns 404.

The correct one is: https://catalog.ldc.upenn.edu/LDC2008T19

**Comment by IbtihalFerwana** [comment]
@raffaem At the `Data` section of the link provided, when I click `News Industry Text Format (NITF) ` to get the xml files it returns 404. Any idea on where to get the corpus?

**Comment by raffaelemancuso** [comment]
> @raffaem At the `Data` section of the link provided, when I click `News Industry Text Format (NITF) ` to get the xml files it returns 404. Any idea on where to get the corpus?

You need to login and buy it
